// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1bVduvDG36DQNorvV0AftVmL4IOUvZhM',
    appId: '1:589839286692:web:054e6c2a3ef37b2bbf4131',
    messagingSenderId: '589839286692',
    projectId: 'tasty-ded39',
    authDomain: 'tasty-ded39.firebaseapp.com',
    storageBucket: 'tasty-ded39.appspot.com',
    measurementId: 'G-YRRJ5TLJ9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaFcyWa1JH0knBBvAzOa0Riux-GwoN_AE',
    appId: '1:296049155903:android:b62217bd44af5a4b173d8a',
    messagingSenderId: '296049155903',
    projectId: 'moeen_provider-4e3a6',
    storageBucket: 'moeen_provider-4e3a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD35p-jyBfGaqbNz2jvkwWosC1-1USuHvE',
    appId: '1:296049155903:ios:be8030ccccacf270173d8a',
    messagingSenderId: '296049155903',
    projectId: 'moeen_provider-4e3a6',
    storageBucket: 'moeen_provider-4e3a6.appspot.com',
    iosBundleId: 'main.moeen_provider.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5fw7rQCDhLwlSCaGSShxzhgK5IBUJkfw',
    appId: '1:589839286692:ios:326e4346c787a915bf4131',
    messagingSenderId: '589839286692',
    projectId: 'tasty-ded39',
    storageBucket: 'tasty-ded39.appspot.com',
    iosBundleId: 'main.moeen_provider.app.RunnerTests',
  );
}
